name: 🐍 Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: naimurhamim
          outputs: |
            dist/snake-dark.svg?palette=github-dark
            dist/snake-green.svg?color_snake=a7c957&color_dots=#6a994e,#a7c957,#386641,#f2e8cf,#bc4749
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push SVG to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
